name: app_formularis
description: "An easy app to start using forms"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0-dev.1
  form_builder_validators: ^11.0.0
  flutter_typeahead: ^5.2.0
  cupertino_icons: ^1.0.8
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true